# Generated by Django 3.2.5 on 2021-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='neptun',
            field=models.CharField(default='N3PTUN', max_length=6),
        ),
    ]
