# Generated by Django 3.2.5 on 2021-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_neptun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='neptun',
            field=models.CharField(default='N3PTUN', max_length=6, unique=True),
        ),
    ]
