# Generated by Django 3.2.5 on 2021-08-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210813_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='systemuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.systemuser'),
        ),
    ]
