# Generated by Django 3.2.5 on 2021-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokerauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
