# Generated by Django 3.2.5 on 2021-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokerauth', '0005_alter_sshkey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='pubkey',
            field=models.TextField(unique=True),
        ),
    ]
